import pandas as pd
import numpy as np
df = pd.read_csv("ecommerce_data_150_rows.csv")
print("E-COMMERCE DATASET")
print(df)
print("\nSHAPE")
print(df.shape)
print("\nCOLUMNS")
print(df.columns)
print("\nDATA TYPES")
print(df.dtypes)
print("\nMISSING VALUES")
print(df.isnull().sum())
print("\nTOTAL MISSING VALUES")
print(df.isnull().sum().sum())
print("\nDUPLICATE ROWS")
print(df.duplicated())
print("\nTOTAL DUPLICATE ROWS")
print(df.duplicated().sum())